#!/usr/bin/env python

import MySQLdb
from time import sleep

host = 'localhost'
user = 'root'
passwd = ''

newuser = ''
newpass = ''
newdb = ''

try:
    db = MySQLdb.connect(host, user, passwd)
except MySQLdb.Error, e:
    print "Error %d: %s" %(e.args[0], e.args[1])
    sys.exit(1)

print 'Connected'


query1 = "CREATE DATABASE IF NOT EXISTS %s" % newdb

query2 = """CREATE USER '%s'@'localhost' IDENTIFIED BY '%s'""" % (newuser, newpass)

query3 = "GRANT ALL PRIVILEGES ON  %s . * TO  '%s'@'localhost' WITH GRANT OPTION" % (newdb, newuser)

query4 = "USE %s" % newdb

query5 = """
CREATE TABLE IF NOT EXISTS `control` (
  `state` varchar(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `control` (`state`) VALUES
('play');
"""

query6 = """
CREATE TABLE IF NOT EXISTS `logs` (
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `message` text NOT NULL,
  KEY `timestamp` (`timestamp`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
"""

query7 = """
CREATE TABLE IF NOT EXISTS `patchinfo` (
  `name` varchar(40) NOT NULL,
  `playNum` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
"""

query8 = """
CREATE TABLE IF NOT EXISTS `playing` (
  `current` varchar(40) NOT NULL,
  `previous` varchar(40) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `playing` (`current`, `previous`) VALUES
('none', 'none');
"""

cursor = db.cursor()

cursor.execute(query1)
cursor.execute(query2)
cursor.execute(query3)
cursor.execute(query4)
cursor.execute(query5)
cursor.close()

cursor = db.cursor()
cursor.execute(query6)
cursor.close()

cursor = db.cursor()
cursor.execute(query7)
cursor.close()

cursor = db.cursor()
cursor.execute(query8)
cursor.close()

