#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

This script sets up PatchWerk Radio

OPTIONS:
   -h   Show this message

   -d   The PatchWerk Radio repository
            If this is provided then anything in
            the install directory will be deleted
            and the contents of this folder copied
            into it

   -p   The Radio Patches repository
            If this is provided then again anything
            in the standard patches directory will
            be deleted and the contents of this
            folder copied into it

   -c   The configfile
            This file will be copied into the install
            directory

   -n   The name of the PatchWerk instance
            PatchWerk Radio will be installed in this
            directory in /usr/local/sbin
            This will also be used as the name for the
            working and run directories
            Defaults to TestPatchWerk

   -b   The git branch to checkout
            Only for PatchWerk Radio
            Radio-Patches always uses 'master'
            Defaults to master
EOF
}

INSTNAME=TestPatchWerk
BRANCH=master
CONFIG=
APPREPO=
PATCHREPO=

while getopts "n:b:c:d:p:" OPTION
do
    case $OPTION in
        h)
            usage
            exit 1
            ;;
        n)
            INSTNAME=$OPTARG
            ;;
        b)
            BRANCH=$OPTARG
            ;;
        c)
            CONFIG=$OPTARG
            ;;
        d)
            APPREPO=$OPTARG
            ;;
        p)
            PATCHREPO=$OPTARG
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done


BINDIR=/usr/local/sbin/$INSTNAME
WORKDIR=/var/$INSTNAME
PATCHDIR=$WORKDIR/patches
TMPDIR=$WORKDIR/temp
RUNDIR=/var/run/$INSTNAME

cd $APPREPO
sudo -u guy git checkout $BRANCH

if [ -n $PATCHREPO ]
then
    cd $PATCHREPO
    sudo -u guy git checkout master
fi


if [ -d $BINDIR ]
then
    rm -r $BINDIR
fi
mkdir -p $BINDIR
cp -r $APPREPO/app/* $BINDIR/

if [ -f $CONFIG ]
then
    cp  $CONFIG $BINDIR/
fi

chown -R patchwerk:radio $BINDIR


if [ -n $PATCHREPO ]
then
    if [ -d $WORKDIR ]
    then
        rm -r $WORKDIR
    fi
    mkdir -p $WORKDIR
    mkdir -p $PATCHDIR
    mkdir -p $TMPDIR

    cp -r $PATCHREPO/* $PATCHDIR/
    rm -r $PATCHDIR/README
    rm -r $PATCHDIR/misc
fi

if [ ! -d $RUNDIR ]
then
    mkdir -p $RUNDIR
fi

chown -R patchwerk:radio $WORKDIR
chown -R patchwerk:radio $RUNDIR
chmod -R 755 $WORKDIR


