#! /bin/sh
# example python daemon starter script
# based on skeleton from Debian GNU/Linux
# cliechti@gmx.net
# place the daemon scripts in a folder accessible by root. /usr/local/sbin is a good idea

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/sbin/RadioDrone.py
NAME=radioServer
DESC="Radio PD daemon"

test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
        $DAEMON start
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
        $DAEMON stop
	echo "$NAME."
	;;
  restart)
	echo -n "Restarting $DESC: "
        $DAEMON restart
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0