#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

FOLDER=/usr/local/sbin/PatchWerk-Radio

DAEMON=$FOLDER/Radio.py
CONFIG=$FOLDER/config.cfg

exec 2>&1
exec setuidgid patchwerk $DAEMON -c $CONFIG
